apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-operator
spec:
  selector:
    matchLabels:
      app: minecraft-operator
  template:
    metadata:
      labels:
        app: minecraft-operator
    spec:
      serviceAccountName: minecraft-operator
      containers:
        - image: steve-meierhofer.com/minecraft-operator
          name: minecraft-operator
